import { Router } from "express";
import { z } from "zod";
import {
  supplierFormInputSchema,
  attachmentRefSchema,
  calculateVat,
  calculatePriceIncludingVat,
  PAYMENT_TERMS,
} from "@workspace/procurement";
import { safeJsonResponse, errorJsonResponse } from "../lib/response";

// ─── Phase B body schema ──────────────────────────────────────────────────────
// Derived from the canonical SupplierFormInput from @workspace/procurement.
// Attachment fields are optional in Phase B because the full upload flow
// (pre-upload → get storage URL → include in submission) is not yet wired up.
//
// Phase C will replace this with the full supplierFormInputSchema once:
//   1. The file upload proxy endpoint exists (POST /api/public/upload/:token)
//   2. AttachmentRef URLs are generated server-side before form submission
//   3. Firestore writes are enabled

const phaseBPublicSubmissionSchema = supplierFormInputSchema
  .omit({
    commercialRegistrationAttachment: true,
    accreditationAttachment: true,
    nationalAddressAttachment: true,
    ibanAttachment: true,
    extraAttachments: true,
  })
  .extend({
    // Attachments optional in Phase B — they WILL be required in Phase C.
    commercialRegistrationAttachment: attachmentRefSchema.optional(),
    accreditationAttachment: attachmentRefSchema.optional(),
    nationalAddressAttachment: attachmentRefSchema.optional(),
    ibanAttachment: attachmentRefSchema.optional(),
    extraAttachments: z.array(attachmentRefSchema).optional(),
  });

// ─── Router ───────────────────────────────────────────────────────────────────

const router = Router();

/**
 * POST /api/public/supplier-response/:token
 *
 * Public endpoint — no authentication required.
 * The supplier opens a link generated by Procurement, fills the form, and
 * submits to this endpoint.  The :token identifies which supplier_link
 * document the submission belongs to.
 *
 * TODO (Phase C): Look up the token in Firestore supplier_links collection.
 * TODO (Phase C): Validate isActive == true and expiresAt has not passed.
 * TODO (Phase C): Enforce one-submission-per-link (responseId must be null).
 * TODO (Phase C): Write the supplier_responses document via getAdminDb().
 * TODO (Phase C): Update supplier_links.responseId and supplier_links.submittedAt.
 * TODO (Phase C): Append a workflow_events document (type: supplier_response_received).
 * TODO (Phase C): Replace phaseBPublicSubmissionSchema with supplierFormInputSchema.
 */
router.post("/supplier-response/:token", (req, res) => {
  const { token } = req.params;

  // Basic token format check — a real token is 64 hex chars (32 random bytes).
  if (!token || token.length < 32) {
    return errorJsonResponse(res, "Invalid or missing supplier link token.", 400);
  }

  const parsed = phaseBPublicSubmissionSchema.safeParse(req.body);

  if (!parsed.success) {
    req.log.warn(
      { token, validationError: parsed.error.flatten() },
      "public supplier-response body invalid",
    );
    return errorJsonResponse(res, parsed.error.message, 400);
  }

  const body = parsed.data;

  // Compute VAT and total using helpers from @workspace/procurement.
  const vatAmountSar = calculateVat(body.priceExcludingVatSar);
  const priceIncludingVatSar = calculatePriceIncludingVat(body.priceExcludingVatSar);

  req.log.info(
    { token, priceExcludingVatSar: body.priceExcludingVatSar, vatAmountSar, priceIncludingVatSar },
    "public supplier-response received (Phase B — not yet persisted)",
  );

  // Phase B: return computed totals without writing to Firestore.
  // Remove _phase and _todo keys once Phase C Firestore write is implemented.
  return safeJsonResponse(
    res,
    {
      _phase: "B_FOUNDATION",
      _todo: "Token validation and Firestore write will be added in Phase C.",
      computedTotals: {
        priceExcludingVatSar: body.priceExcludingVatSar,
        vatAmountSar,
        priceIncludingVatSar,
        vatRatePercent: 15,
      },
      receivedFields: Object.keys(body),
    },
    202,
  );
});

export default router;
